#!/bin/sh

ARRAY=()
ARRAY2=()

for num in {1..35}
do
    lp=$(printf "80%02d" $num)
    lp2=$(printf "60%02d" $num)
    gp=$(printf "gp%02d" $num)
    ARRAY[num]="-L ${lp}:${gp}:8000"
    ARRAY2[num]="-L ${lp2}:${gp}:6006"
done

ssh -t ${ARRAY[*]} ${ARRAY2[*]} im00

